FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf
RUN rm -rf /sbin/apk /etc/apk /lib/apk /var/cache/apk

#add User
RUN addgroup -S nginxgroup && adduser -S nginxuser -G nginxgroup

# Copy our custom Nginx config
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

# Copy Laravel app static files (e.g. public) for deployment
COPY . /var/www/html

# Ensure permissions are correct
RUN chown -R nginxuser:nginxgroup /var/www/html /var/cache/nginx && \
    chmod -R ugo+rwx /var/www/html /var/cache/nginx

USER nginxuser

EXPOSE 8081

CMD ["nginx", "-g", "daemon off;"]
