apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
data:
  config.json: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImRHRnNhR0Y2WVdaaGNuTmlNVG9oUUdKMVoyUmxZVXd6Y2c9PSIKCQl9Cgl9Cn0=
