version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-appp
    image: app                                    #add dockker repository of images:tag and remove build, context and dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_lms
      DB_USERNAME: root
      DB_PASSWORD: '!@bugdeaL3r'
    working_dir: /var/www/html
#also remove this line remove "volume
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginxx
    image: nginx                                  #do the same for this  remove build, context and dockerfile and add images docker address
    container_name: nginx
    ports:
      - "8081:8081"
    depends_on:
      - app
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_lms
#      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '!@bugdeaL3r'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
#for run pushed images to other pc/os
