# Stage 1 - Build
FROM nginx:alpine AS builder

RUN apk update && apk upgrade  # Add this to get updated packages

# Remove default config and set up files
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY . /var/www/html

# Stage 2 - Final runtime image
FROM nginx:alpine

RUN apk update && apk upgrade  # Ensure latest patched packages are installed

# Add user
RUN addgroup -S nginxgroup && adduser -S nginxuser nginxgroup

# Remove apk-tools (and dependencies that can be purged)
RUN apk --no-cache add --virtual .run-deps nginx \
    && apk --no-cache del apk-tools

# Copy only necessary files from builder
COPY --from=builder /etc/nginx /etc/nginx
COPY --from=builder /var/www/html /var/www/html

# Set ownership and permissions
RUN chown -R nginxuser:nginxgroup /var/www/html /var/cache/nginx && \
    chmod -R ugo+rwx /var/www/html /var/cache/nginx

USER nginxuser
EXPOSE 8081
CMD ["nginx", "-g", "daemon off;"]
