FROM php:8.0-fpm

# Set working directory
WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    apt-utils \
    dpkg \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    nano \
    unzip \
    git \
    curl \
    libzip-dev \
    npm \
    && docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath gd

#add appuser
RUN addgroup --system apuser && adduser --system --ingroup apuser appuser

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy existing application directory contents
COPY . /var/www/html

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader
RUN php artisan key:gen

# Set permissions
RUN chown -R appuser:apuser /var/www/html && \
    chmod -R ugo+rwx /var/www/html storage/ storage/logs/ bootstrap/cache/ .env


#switch user

USER appuser

# Expose port
EXPOSE 9000

CMD ["php-fpm"]
