# Use an official PHP image with Apache
FROM php:8.0-fpm-alpine

# Install required PHP extensions
RUN apk add --no-cache \
    nano \
    bash \
    shadow \
    curl \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    zip \
    unzip \
    icu-dev \
    libxml2-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd intl pdo pdo_mysql mysqli xml opcache

# Install Composer
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy Laravel files into container
COPY . /var/www/html

# Give proper permissions
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R ugo+rwx /var/www/html/storage /var/www/html/bootstrap/cache

# Expose port 9000
EXPOSE 9000

# Start 
CMD ["php-fpm"]
