version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: app
    container_name: app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_DATABASE: db_lms
      DB_USERNAME: root
      DB_PASSWORD: '!@bugdeaL3r'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx
    container_name: nginx
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_lms
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
      MYSQL_PASSWORD: '!@bugdeaL3r'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
