version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: app
    container_name: app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db_lms
      - DB_USERNAME=root
      - DB_PASSWORD=!@bugdeaL3r

  web:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: db_lms
      MYSQL_ROOT_PASSWORD: '!@bugdeaL3r'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
