apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: custom-git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "tekton"
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      script: |
        rm -rf $(workspaces.output.path)/*
        rm -rf $(workspaces.output.path)/.[!.]* $(workspaces.output.path)/..?*
        git clone -b $(params.revision) $(params.url) $(workspaces.output.path)
