apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: lms-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: "tekton"
    - name: image-reference
      type: string
    - name: app-image
      type: string
    - name: nginx-image
      type: string
  workspaces:
    - name: shared-workspace
    - name: docker-credentials
  tasks:
    - name: clone-repo
      taskRef:
        name: custom-git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: install-composer
      runAfter: [clone-repo]
      taskRef:
        name: composer-install
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: run-tests
      runAfter: [install-composer]
      taskRef:
        name: run-php-tests
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-app
      runAfter: ["run-tests"]
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE
          value: $(params.app-image)
        - name: DOCKERFILE
          value: Dockerfile-app
        - name: CONTEXT
          value: .
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerConfig
          workspace: docker-credentials

    - name: build-nginx
      runAfter: ["build-app"]
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE
          value: $(params.nginx-image)
        - name: DOCKERFILE
          value: Dockerfile-nginx
        - name: CONTEXT
          value: .
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerConfig
          workspace: docker-credentials
