apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: lms-pipeline-run
spec:
  pipelineRef:
    name: lms-pipeline
  params:
    - name: repo-url
      value: https://github.com/talhazafarsb/lms.git
    - name: revision
      value: tekton
    - name: image-reference
      value: docker.io/talhazafarsb1/app:tkn
    - name: app-image
      value: docker.io/talhazafarsb1/app:tkn
    - name: nginx-image
      value: docker.io/talhazafarsb1/nginx:tkn
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: pipeline-run-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
         secretName: docker-credentials