apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params:
  - name: repo-url
    value: https://github.com/talhazafarsb/lms.git
  - name: revision
    value: tkn-tutorial
  - name: image-reference
    value: docker.io/talhazafarsb1/app:key
  - name: DOCKERFILE
    value: Dockerfile-app
  - name: CONTEXT
    value: .