apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: db_lms
  DB_USERNAME: root
  DB_PASSWORD: '!@bugdeaL3r'
  APP_KEY: base64:992v8I4wKu7byKL1oLQuKsq7yysM1b7cIhPeOxtA4Dc=
