apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: custom-sa
      automountServiceAccountToken: false
      containers:
        - name: app
          image: quay.io/talhazafarmlynx/app:oenv
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_HOST
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - port: 9000
      targetPort: 9000
